spring.application.name=DineLock

# Sunucu Portu
server.port=8080

# MySQL Bağlantı Ayarları
spring.datasource.url=jdbc:mysql://localhost:3306/dinelock?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456

# Hibernate & JPA Ayarları
# update: Proje çalıştığında tablolar yoksa oluşturur, varsa günceller.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Google Gemini API Settings (Güvenli Çevresel Değişken Kullanımı)
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=
gemini.api.key=${GEMINI_API_KEY}
